### ISSUE TITLE
Task title used as unique identifier

### ISSUE THREAD

**Issue by mshaneck** [Simspace/pycep#19]
**Describe the bug**
The task title is used as the unique identifier. If multiple tasks have the same title, then only one survives the export.

**To Reproduce**
Export an SCP that has multiple tasks with the same title. 

**Expected behavior**
I would expect all the tasks to survive, using the task id as the identifier.

**Comment by wroersma** [comment]
For now this will not be resolved as the title format wouldn't work with markdown format at all.
